python run_config.py ./Config/Dspell_real_vary.yaml
python run_config.py ./Config/Lspell_real_vary.yaml
python run_config.py ./Config/Dspell_pcvd_vary.yaml
python run_config.py ./Config/Lspell_pcvd_vary.yaml
python run_config.py ./Config/BonusDeep_vary.yaml
python run_config.py ./Config/BonusUnemp_vary.yaml
python run_config.py ./Config/UpdatePrb_vary.yaml
python run_config.py ./Config/StimMax_vary.yaml
python run_config.py ./Config/StimCut0_vary.yaml
python run_config.py ./Config/StimCut1_vary.yaml
python run_config.py ./Config/UnempD_vary.yaml
python run_config.py ./Config/UnempH_vary.yaml
python run_config.py ./Config/UnempC_vary.yaml
python run_config.py ./Config/UnempP_vary.yaml
python run_config.py ./Config/UnempA1_vary.yaml
python run_config.py ./Config/DeepD_vary.yaml
python run_config.py ./Config/DeepH_vary.yaml
python run_config.py ./Config/DeepC_vary.yaml
python run_config.py ./Config/DeepP_vary.yaml
python run_config.py ./Config/DeepA1_vary.yaml
